#!/bin/sh

# standard stuff
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkdir="mkdir -pv"

# use colors where possible
alias \
    ls="ls -h --color=auto" \
    grep="grep --color=auto" \
	diff="diff --color=auto"

# ls abbreviations
alias \
	ll="ls -hlA --color=auto" \
	la="ls -hAC --color=auto"

# wget: clean up home
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'

# yarn: clean up home
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/yarnrc"'

# manage dotfiles using git
alias \
    lgdf="lazygit --git-dir=\"$HOME/dotfiles/.git/\" --work-tree=\"$HOME/dotfiles/\"" \
    gitdf="git -C \"$HOME/dotfiles\""

alias lg=lazygit
