return {
  {
    "zbirenbaum/copilot-cmp",
    enabled = false,
  },
--  {
--    "zbirenbaum/copilot.lua",
--    cmd = "Copilot",
--    build = ":Copilot auth",
--    event = "InsertEnter",
--    opts = {
--      panel = {
--        enabled = true,
--        auto_refresh = false,
--        keymap = {
--          jump_prev = "<C-S-p>",
--          jump_next = "<C-S-n>",
--          accept = "<CR>",
--          refresh = "<Leader>rr",
--          open = false,
--        },
--        layout = {
--          position = "bottom", -- | top | left | right
--          ratio = 0.4,
--        },
--      },
--      suggestion = {
--        enabled = true,
--        auto_trigger = true,
--        debounce = 50,
--        keymap = {
--          accept = "<C-CR>",
--          accept_word = "<C-S-CR>",
--          accept_line = false,
--          next = "<C-S-n>",
--          prev = "<C-S-p>",
--          dismiss = "<C-S-c>",
--        },
--      },
--      filetypes = {
--        yaml = false,
--        markdown = false,
--        help = false,
--        gitcommit = false,
--        gitrebase = false,
--        hgcommit = false,
--        svn = false,
--        cvs = false,
--        ["."] = false,
--      },
--      copilot_node_command = "node", -- Node.js version must be > 18.x
--      server_opts_overrides = {},
--    },
--  },
  --{
  --  "nvim-lualine/lualine.nvim",
  --  optional = true,
  --  event = "VeryLazy",
  --  opts = function(_, opts)
  --    table.insert(
  --      opts.sections.lualine_x,
  --      2,
  --      LazyVim.lualine.status(LazyVim.config.icons.kinds.Copilot, function()
  --        local clients = package.loaded["copilot"] and LazyVim.lsp.get_clients({ name = "copilot", bufnr = 0 }) or {}
  --        if #clients > 0 then
  --          local status = require("copilot.api").status.data.status
  --          return (status == "InProgress" and "pending") or (status == "Warning" and "error") or "ok"
  --        end
  --      end)
  --    )
  --  end,
  --}
}
