import = ["/Users/louvan/.config/alacritty/kanagawa_wave.toml"]

[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[window]
dynamic_title = true
opacity = 0.999

[window.dimensions]
columns = 152
lines = 60

[keyboard]
bindings = [
    { key = "PageUp",   mods = "Shift",         action = "ScrollLineUp"},
    { key = "PageUp",   mods = "Control",       action = "ScrollHalfPageUp"},
    { key = "PageDown", mods = "Shift",         action = "ScrollLineDown"},
    { key = "PageDown", mods = "Control",       action = "ScrollHalfPageDown"},
    { key = "Tab",      mods = "Control",       action = "SelectNextTab"},
    { key = "Tab",      mods = "Control|Shift", action = "SelectPreviousTab"},
]
