#!/usr/bin/env zsh

antigen use oh-my-zsh

# load plugins
antigen bundles <<EOBUNDLES
  zdharma-continuum/fast-syntax-highlighting
  zsh-users/zsh-autosuggestions@master
EOBUNDLES
#  lukechilds/zsh-nvm
#  agkozak/zsh-z

antigen theme romkatv/powerlevel10k

antigen apply
